services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  PromotionTourWebsite\PromotionEvents\:
    resource: "../Classes/*"
    exclude:
      - "../Classes/Domain/Model/*"
